change code-server title
railwayapp/starters pull request #147
Opened 2021-06-21 12:25 UTC by bpmct

I noticed the description had it as "code-server," but I made a couple of changes to explain what code-server is and fix the heading. Totally understand if you want to keep the current description, this is just a suggestion :)

2021-06-21 13:10 UTC, FarazPatankar commented
Thanks for the PR, @bpmct. Cool if we only update the description? Would be nice to keep the title consistent across all starters.

![starters@2x](https://user-images.githubusercontent.com/10681116/122767273-7b325b80-d270-11eb-9824-1ca01ad8283d.png)

2021-06-21 14:41 UTC, bpmct commented
that works!

2021-06-25 13:53 UTC, 1chiSensei requested changes

2021-06-25 13:53 UTC, 1chiSensei commented on examples/code-server/README.md
>  This example is maintained by the [Coder](https://coder.com/) team and the source code can be found [here](https://github.com/cdr/deploy-code-server).
```suggestion
This example is maintained by the [Coder](https://coder.com/) team and the source code can be found [here](https://github.com/cdr/code-server).
```

Isn't that repo used to list on how to deploy `code-server`?

2021-06-25 19:21 UTC, coffee-cup commented on examples/code-server/README.md
> +title: code-server
As per the discussion, going to keep the title Code Server :)
```suggestion
title: Code Server
```

2021-06-25 19:21 UTC, merged